## 安裝及引入
!pip install numpy

import numpy as np

## 轉換資料型態

＄ umPy 在定義陣列時，可以透過 dtype 指定資料的型態，就能將陣列內的所有資料轉變成對應的型態 

In [2]:
import numpy as np

a = np.array([1.1, 2.2, 3.3, 0, -1])
# 使用 bool 类型的数据类型（布尔型）
b = np.array(a, dtype='?')
# 使用 Unicode 字符串数据类型
c = np.array(a, dtype='U')
# 使用字节字符串数据类型
d = np.array(a, dtype='S')
# 使用无符号整数数据类型（布尔型）
e = np.array(a, dtype='B')
# 使用整数数据类型
f = np.array(a, dtype='I')

/var/folders/sw/9p5t6n_s5slgb49wh4jkfkk00000gn/T/ipykernel_3458/704477725.py:13: RuntimeWarning: invalid value encountered in cast
  f = np.array(a, dtype='I')


## 取得資料型態

In [3]:
a = np.array([1,2,3,4,5])
print(a.dtype)    # int64

int64


## 建立陣列的方法

In [6]:
# numpy.array()
a = np.array([1,2,3,4], dtype=int)                      # 建立一維陣列
b = np.array([[1,2],[3,4]])                  # 建立二維陣列

# numpy.empty() 可以建立指定大小的空陣列
a = np.empty(2)        # 建立一維空陣列
b = np.empty([2,2])    # 建立二維空陣列

# numpy.zeros() 可以建立每個項目數值為 0 的陣列。
a = np.zeros(2)        # 建立一維 zero 陣列
b = np.zeros([2,2])    # 建立二維 zero 陣列

# numpy.ones() 可以建立每個項目數值為 1 的陣列。
a = np.ones(2)        # 建立一維 one 陣列
b = np.ones([2,2])    # 建立二維 one 陣列

# numpy.eye() 可以建立對角線項目為 1，其他項目為 0 的陣列。
print(np.eye(3))     # 建立 3x3 陣列，對角線起始點為 0
print(np.eye(3,5))   # 建立 3x5 陣列，對角線起始點為 0
print(np.eye(3,5,2)) # 建立 3x3 陣列，對角線起始點為 2


# numpy.tile() 會複製現有的陣列的內容，依據新的維度建立新陣列。
a = np.array([1,2,3])
b = np.tile(a, 5)       # [1,2,3] 重複 5 次變成一維陣列
c = np.tile(a, (5, 2))  # [1,2,3] 重複放入 5x2 的陣列中

# numpy.arange() 可以建立兩個數值間，指定「間距」的「等差」連續資料的陣列，支援小數點的間隔 ( 設定 dtype 可指定資料型態 )。
a = np.arange(10)        # 建立 1～10，間隔為 1 的陣列
b = np.arange(5,10, dtype='float')      # 建立 5～10，間隔為 1 的陣列
c = np.arange(5,10,0.1)  # 建立 5～10，間隔為 0.1 的陣列

# numpy.linspace() 可以建立兩個數值間，指定「數量」的「等差」連續資料陣列，( 額外設定 endpoint False 表示不包含最後一個數字、設定 dtype 可指定資料型態 )。
a = np.linspace(5, 10, 10)        # 建立 5～10，內容有 10 個項目的陣列
c = np.linspace(5, 10, 10, dtype='int')       # 建立 5～10，內容有 10 個「整數」項目的陣列

## 讀取陣列

In [7]:
# 索引值讀取
a = np.array([1,2,3,4,5])
print(a[0])    # 1
print(a[1])    # 2

a = np.array([[1,2,3],[4,5,6]])
print(a[0,0])  # 1
print(a[1,1])  # 5

1
2
1
5


In [8]:
# 切片讀取 
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
print(a[2:5])   # [3 4 5]              從第三項取值到第五項 ( 不包含第六項 )
print(a[:5])    # [1 2 3 4 5]          從第一項取值到第五項 ( 不包含第六項 )
print(a[2:])    # [3 4 5 6 7 8 9]      從第三項開始取值
print(a[2:-1])  # [3 4 5 6 7 8]        從第三項取值到倒數第二項
print(a[::2])   # [1 3 5 7 9]          間隔 2 取值
print(a[2:8:2]) # [3 5 7]              第三項到第七項，間隔 2 取值
print(a[::-1])  # [9 8 7 6 5 4 3 2 1]  反轉

[3 4 5]
[1 2 3 4 5]
[3 4 5 6 7 8 9]
[3 4 5 6 7 8]
[1 3 5 7 9]
[3 5 7]
[9 8 7 6 5 4 3 2 1]


## 迭代陣列

In [9]:
# numpy.ndenumerate() 會回傳迭代陣列時，該元素的索引值，下方的例子會印出這個元素的位置 ( 例如 4 位在 [0,1,0] 的位置 )
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i,j in np.ndenumerate(a):
    print(i,j)


(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


## 修改陣列形狀

In [11]:
# reshape() 可以將現有的陣列，轉換為特定維度的陣列
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = a.reshape((4,2))
print(b)
c = a.reshape((2,4))
print(c)
print()

# 如果轉換時不確定該維度要具有多少個項目，可使用「-1」代替，下方的例子會將一個 4x2 的二維陣列，變成一維陣列、2x4 陣列以及三維陣列。
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.reshape(-1)        # 轉換成一維陣列
print(b)                 # [1 2 3 4 5 6 7 8]
c = a.reshape((2,-1))    # 等同 a.reshape((2,4))
print(c)
d = a.reshape((2,2,-1))  # 等同 a.reshape((2,2,2))
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# flatten() 和 numpy.ravel() 能將多維度的陣列，扁平化成一維陣列
# 可以設定 order 參數調整扁平的順序:
# 預設為 C，表示先水平再垂直，
# 設定為 F 表示先垂直再水平。

import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.flatten('C')    # [1 2 3 4 5 6 7 8]
c = a.flatten('F')    # [1 2 3 4 5 6 7 8]
b1 = np.ravel(a,'C')  # [1 3 5 7 2 4 6 8]
c1 = np.ravel(a,'K')  # [1 2 3 4 5 6 7 8]

In [14]:
# numpy.transpose() 和 T 轉至
import numpy as np

a = np.array([[1,2],[3,4]])
b = a.T
c = np.transpose(a)
print(b)
print(c)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


## numpy.rollaxis() 和 numpy.swapaxes() 會根據指定「軸」，將陣列項目滾動改變或交換位置，下圖為一個陣列的「軸」的示意。
![upgit_20240429_1714323657.png](https://raw.githubusercontent.com/kcwc1029/obsidian-upgit-image/main/2024/04/upgit_20240429_1714323657.png)

## 修改陣列項目

In [15]:
"""
numpy.resize() 會將原本的陣列調整為新的尺寸，運作原理是先把原本陣列的元素攤平，
再依序放入新尺寸的陣列中，若新尺寸大於原本的項目數量，就依序重複放入，
如果新尺寸小於原本的數量，就會捨棄超過的項目。
"""
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.resize(a, (3,2))
c = np.resize(a, (5,5))
d = np.resize(a, (2,2))
b, c, d


(array([[1, 1],
        [1, 2],
        [2, 2]]),
 array([[1, 1, 1, 2, 2],
        [2, 1, 1, 1, 2],
        [2, 2, 1, 1, 1],
        [2, 2, 2, 1, 1],
        [1, 2, 2, 2, 1]]),
 array([[1, 1],
        [1, 2]]))

In [20]:
# numpy.append() 會將項目添加到陣列最後面，並返回一個一維陣列
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.append(a, 1)
c = np.append(a, [3,3,3])
print(b, c)
print()

# 可以設定第三個參數 ( 預設 None ) 為 0 ( 行 ) 或 1 ( 列 )，指定資料插入的維度。
b = np.append(a, [[3,3,3],[4,4,4]],1)
c = np.append(a, [[3,3,3],[4,4,4]],0)
b, c

[1 1 1 2 2 2 1] [1 1 1 2 2 2 3 3 3]



(array([[1, 1, 1, 3, 3, 3],
        [2, 2, 2, 4, 4, 4]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [21]:
"""
numpy.insert() 會將項目添加到陣列指定的位置，並返回一個一維陣列，
第三個參數是要加入的內容，如果設定第四個參數 ( 預設 None ) 為 0 ( 行 ) 或 1 ( 列 )，則可以指定資料插入的維度。
"""
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a, 1, [4,4])
c = np.insert(a, 2, [4,4])
d = np.insert(a, 2, [4,4], 0) 
b, c, d

(array([1, 4, 4, 1, 2, 2, 3, 3]),
 array([1, 1, 4, 4, 2, 2, 3, 3]),
 array([[1, 1],
        [2, 2],
        [4, 4],
        [3, 3]]))

In [24]:
# numpy.delete() 會將項目刪除陣列中指定位置的項目，並返回一個一維陣列
# 如果設定第三個參數 ( 預設 None ) 為 0 ( 行 ) 或 1 ( 列 )，則可以指定資料插入的維度。
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
b = np.delete(a, 1)
c = np.delete(a, 2)
d = np.delete(a, 2, 0)
b,c,d


(array([1, 3, 4, 5, 6]),
 array([1, 2, 4, 5, 6]),
 array([[1, 2],
        [3, 4]]))

In [25]:
"""
numpy.unique() 會取出不重複的項目，返回一個一維陣列
- return_index	如果為 True，返回取出的元素在原來列表中的位置。
- return_inverse	如果為 True，返回原本的元素在新列表中的位置。
- return_counts	如果為 True，返回取出的項目在原本列表中出現的次
"""
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.unique(a)
c = np.unique(a, return_index=True)
d = np.unique(a, return_inverse=True)
e = np.unique(a, return_counts=True)
b, c,d,e

(array([1, 2, 3]),
 (array([1, 2, 3]), array([0, 2, 4])),
 (array([1, 2, 3]), array([0, 0, 1, 1, 2, 2])),
 (array([1, 2, 3]), array([2, 2, 2])))

## 填充陣列
＄ numpy.pad() 填充陣列時能設定填充模式，預設使用 constant 填充相同的數值 ( 預設 0 )
- constant	連續填充相同值 ( 預設 )，預設填入 0，也可指定單一填充數值，或使用 (x,y) 表示左方空缺填入 x，右方空缺填入 y。
- edge	邊緣填充，右方空缺填入與最右方項目相同的值，左方空缺填入與最左方項目相同的值。
- linear_ramp	邊緣遞減，空缺處填入逐漸變小的值，直到最小值。
- maximum	最大值填充，空缺處填入原本陣列裡項目的最大值。
- minimum	最小值填充，空缺處填入原本陣列裡項目的最小值。
- mean	平均值填充，空缺處填入陣列項目的平均值。
- median	中位數填充，空缺處填入陣列項目的中位數。
- reflect	反射填充，空缺處填入與陣列項目鏡像反射的數值。
- symmetric	對稱填充，空缺處填入與陣列項目對稱的數值。
- wrap	包裹填充，空缺處填入與陣列重複同樣的數值。

In [29]:
# 填充一維陣列
import numpy as np
a = np.array([-2,-1,0,1,2])
print(np.pad(a,5)) # 左右各多出五個空格，填入 0
print(np.pad(a,5,constant_values = (5,8))) # 左右各多出五個空格，左邊填入 5，右邊填入 8
print()
a = np.array([-2,-1,0,1,2])

# 使用 'edge' 模式填充数组，将数组边界的值复制到边界外的元素
print(np.pad(a, 5, mode='edge'))        # [-2 -2 -2 -2 -2 -2 -1  0  1  2  2  2  2  2  2]
# 使用 'linear_ramp' 模式填充数组，沿着数组边界线性地增加或减少值
print(np.pad(a, 5, mode='linear_ramp')) # [ 0  0  0 -1 -1 -2 -1  0  1  2  1  1  0  0  0]
# 使用 'maximum' 模式填充数组，将数组边界的最大值复制到边界外的元素
print(np.pad(a, 5, mode='maximum'))     # [ 2  2  2  2  2 -2 -1  0  1  2  2  2  2  2  2]
# 使用 'mean' 模式填充数组，将数组边界的均值复制到边界外的元素
print(np.pad(a, 5, mode='mean'))        # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
# 使用 'median' 模式填充数组，将数组边界的中位数复制到边界外的元素
print(np.pad(a, 5, mode='median'))      # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
# 使用 'minimum' 模式填充数组，将数组边界的最小值复制到边界外的元素
print(np.pad(a, 5, mode='minimum'))     # [-2 -2 -2 -2 -2 -2 -1  0  1  2 -2 -2 -2 -2 -2]
# 使用 'reflect' 模式填充数组，对数组边界进行镜像反射填充
print(np.pad(a, 5, mode='reflect'))     # [ 1  2  1  0 -1 -2 -1  0  1  2  1  0 -1 -2 -1]
# 使用 'symmetric' 模式填充数组，对数组边界进行对称填充
print(np.pad(a, 5, mode='symmetric'))   # [ 2  1  0 -1 -2 -2 -1  0  1  2  2  1  0 -1 -2]
# 使用 'wrap' 模式填充数组，将数组视为环形，边界之外的索引从相反的边界处重新开始
print(np.pad(a, 5, mode='wrap'))        # 结果同 'reflect'


[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[ 5  5  5  5  5 -2 -1  0  1  2  8  8  8  8  8]

[-2 -2 -2 -2 -2 -2 -1  0  1  2  2  2  2  2  2]
[ 0 -1 -1 -2 -2 -2 -1  0  1  2  1  1  0  0  0]
[ 2  2  2  2  2 -2 -1  0  1  2  2  2  2  2  2]
[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[-2 -2 -2 -2 -2 -2 -1  0  1  2 -2 -2 -2 -2 -2]
[ 1  2  1  0 -1 -2 -1  0  1  2  1  0 -1 -2 -1]
[ 2  1  0 -1 -2 -2 -1  0  1  2  2  1  0 -1 -2]
[-2 -1  0  1  2 -2 -1  0  1  2 -2 -1  0  1  2]


In [32]:
# 填充多維陣列
# 一維陣列填充後，會自動在「上下左右」擴展出指定的大小
# 可設定上下左右的擴展大小 ( 設定的兩個數值的第一個表示左和上，第二個表示右和下 )，以及填入的數值內容 ( 設定的兩個數值的第一個表示左和上，第二個表示右和下 )。
import numpy as np
a = np.array([[1,1],[2,2]])
print(np.pad(a,1))
print(np.pad(a,1,constant_values = (5,8)))
print()
print(np.pad(a,(1,2)))
print(np.pad(a,(1,2),constant_values = (5,8)))

[[0 0 0 0]
 [0 1 1 0]
 [0 2 2 0]
 [0 0 0 0]]
[[5 5 5 8]
 [5 1 1 8]
 [5 2 2 8]
 [5 8 8 8]]

[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 2 2 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[5 5 5 8 8]
 [5 1 1 8 8]
 [5 2 2 8 8]
 [5 8 8 8 8]
 [5 8 8 8 8]]


## 分割陣列

In [33]:
# numpy.split()、numpy.array_split() 會分割陣列，返回指定數量的新陣列
# 參數：原本的陣列，分割的數量，0 水平分割或 1 為垂直分割。
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array_split(a, 3)
c = np.split(a, 3)
b, c

([array([1, 2]), array([3, 4]), array([5, 6])],
 [array([1, 2]), array([3, 4]), array([5, 6])])

In [34]:
# 將一個二維陣列，按照水平或垂直分割的設定，分割成兩個新陣列 ( 因為數量無法整除，所以不能使用 numpy.split )。
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
b = np.array_split(a, 2)
c = np.array_split(a, 2, 1)
b, c

([array([[1, 2],
         [3, 4]]),
  array([[5, 6]])],
 [array([[1],
         [3],
         [5]]),
  array([[2],
         [4],
         [6]])])

In [36]:
# numpy.hsplit() 會水平分割陣列，返回指定數量的新陣列
# numpy.vsplit 會垂直分割陣列，返回指定數量的新陣列
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.hsplit(a, 3)
c = np.vsplit(a, 3)
b, c


([array([[1],
         [2],
         [3]]),
  array([[1],
         [2],
         [3]]),
  array([[1],
         [2],
         [3]])],
 [array([[1, 1, 1]]), array([[2, 2, 2]]), array([[3, 3, 3]])])

## 合併陣列

In [41]:
# numpy.concatenate() 會將多個「同樣形狀」的陣列，依序連接為新陣列，如果陣列形狀不同，合併會發生錯誤。
a = np.array([1])
b = np.array([2,2])
c = np.concatenate((a, b))

a = np.array([[1,1],[2,2],[3,3]])
b = np.array([[4,4],[5,5],[6,6]])
d = np.concatenate((a, b))
e = np.concatenate((a, b), axis=0)
f = np.concatenate((a, b), axis=1)
c, d, e, f

(array([1, 2, 2]),
 array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6]]),
 array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6]]),
 array([[1, 1, 4, 4],
        [2, 2, 5, 5],
        [3, 3, 6, 6]]))

In [45]:
# numpy.stack() 會將多個「同樣形狀」的陣列，依序堆積為新陣列
a = np.array([1,1])
b = np.array([2,2])
c = np.array([3,3])
d = np.stack((a, b, c))
e = np.stack((a, b), axis=0)  
f = np.stack((a, b), axis=1)  
d, e, f

(array([[1, 1],
        [2, 2],
        [3, 3]]),
 array([[1, 1],
        [2, 2]]),
 array([[1, 2],
        [1, 2]]))

## 陣列排序

In [46]:
"""
# numpy.sort() 會將陣列內容從小到大排序，產生新的陣列。
- axis	排序的維度 ( 軸 )，預設 -1 ( 從最後的軸開始排序 )，可設定 None、0、1。
- kind	排序的演算法，預設 quicksort，另外還有 mergesort、heapsort 和 stable 三種。
- order	如果使用字串定義陣列的欄位，可以用來指定比較的欄位。
"""
a = np.array([5,3,4,2,1,6,7,9,8])
b = np.sort(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# numpy.argsort() 會將陣列從小到大排序後，回傳內容為「索引值」的陣列。
arr = [
  [2,3,7],
  [5,2,6],
  [3,1,2]
]
a = np.array(arr)
b = np.argsort(a)
a, b

(array([[2, 3, 7],
        [5, 2, 6],
        [3, 1, 2]]),
 array([[0, 1, 2],
        [1, 0, 2],
        [1, 2, 0]]))

In [49]:
# numpy.argmax()、numpy.argmin() 會回傳最大值或最小值的「索引值」。
a = np.array([1,2,3,4,5,6,7,8])
b = np.argmax(a)
c = np.argmin(a)
b, c

(7, 0)

## 廣播

In [50]:
# 廣播單一數字
# 將原本陣列的所有元素，根據數學運算式加減乘除廣播的數字，產生新的陣列。
b = 2                     # 廣播單一數字 2
c = np.array([[1,2,3],[4,5,6]])  # 2x3 陣列
print(c+b)    # [[3 4 5] [6 7 8]]
print(c-b)    # [[-1  0  1] [ 2  3  4]]
print(c*b)    # [[ 2  4  6] [ 8 10 12]]
print(c%b)    # [[1 0 1] [0 1 0]]

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[1 0 1]
 [0 1 0]]


In [51]:
# 將某個陣列廣播到另外一個陣列，必須注意在「同一個軸 ( 維度 )」上的數量必須相等或等於 1，不然廣播時會發生錯誤。
a = np.array([[1,1,1],[2,2,2]])   # 2x3 陣列
b = np.array([1,2,3])             # 1x3 陣列
print(a+b)     # [[2 3 4] [3 4 5]]
print(a-b)     # [[ 0 -1 -2] [ 1  0 -1]]
print(a*b)     # [[1 2 3] [2 4 6]]
print(a%b)     # [[0 1 1] [0 0 2]]

c = np.array([[1,1,1],[2,2,2],[3,3,3]])   # 3x3 陣列
d = np.array([[1],[2],[3]])               # 3x1 陣列
print(c+d)     # [[2 2 2] [4 4 4] [6 6 6]]
print(c-d)     # [[0 0 0] [0 0 0] [0 0 0]]
print(c*d)     # [[1 1 1] [4 4 4] [9 9 9]]
print(c%d)     # [[0 0 0] [0 0 0] [0 0 0]]

[[2 3 4]
 [3 4 5]]
[[ 0 -1 -2]
 [ 1  0 -1]]
[[1 2 3]
 [2 4 6]]
[[0 1 1]
 [0 0 2]]
[[2 2 2]
 [4 4 4]
 [6 6 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [4 4 4]
 [9 9 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 搜尋陣列項目

In [52]:
# numpy.where() 會根據判斷式找出索引值，回傳索引值的陣列
a = np.array(['a','b','c','d','a','b','c'])
b = np.where(a=='b')
print(b)

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.where(a>3)
print(b) 
# 對應 (0,3) -> 4
# 對應 (1,0) -> 5

(array([1, 5]),)
(array([0, 1, 1, 1, 1]), array([3, 0, 1, 2, 3]))


In [53]:
# numpy.nonzero() 會取得內容「非 0」的項目索引值，並將索引值回傳為為新陣列。
a = np.array([1,0,1,0,1,0,1,0])
b = np.nonzero(a)
a = np.array([[1,0,1,0],[1,0,1,0]])
c = np.nonzero(a)
b, c

((array([0, 2, 4, 6]),), (array([0, 0, 1, 1]), array([0, 2, 0, 2])))

In [54]:
# numpy.count_nonzero() 會計算陣列中「非 0」項目的數量。
a = np.array([1,0,1,0,1,0,1,0])
np.count_nonzero(a)

4

## 算數計算

In [55]:
x = np.array([[1,1],[1,1]])
y = np.array([[2,2],[3,3]])
np.add(x,y)

array([[3, 3],
       [4, 4]])

In [56]:
x = np.array([[1,1],[1,1]])
y = np.array([[2,2],[3,3]])
np.subtract(x,y)

array([[-1, -1],
       [-2, -2]])

In [59]:
a = np.array([1,2,3])
b = np.array([2,2,2])

x = np.array([[2,3],[2,3]])
y = np.array([[2,2],[3,3]])
np.multiply(a,b), np.multiply(x,y)

(array([2, 4, 6]),
 array([[4, 6],
        [6, 9]]))

In [60]:
a = np.array([5,6,7])
b = np.array([2,2,2])

x = np.array([[5,6],[7,8]])
y = np.array([[2,3],[4,5]])
np.divide(a,b), np.divide(x,y)

# numpy.divide() 會將兩個形狀相同的陣列元素相除，「無條線捨去小數點」後成為新陣列

(array([2.5, 3. , 3.5]),
 array([[2.5 , 2.  ],
        [1.75, 1.6 ]]))

In [63]:
# numpy.divmod() 會將兩個形狀相同的陣列元素相除，將「商」和「餘數」回傳為新陣列。
a = np.array([2,3,4])
b = np.array([3,3,3])
np.divmod(a,b)

(array([0, 1, 1]), array([2, 0, 1]))

In [61]:
# numpy.power() 會以 b 陣列的元素作為 a 陣列元素的次方，計算後成為新陣列
a = np.array([2,3,4])
b = np.array([3,3,3])
np.power(a,b)

array([ 8, 27, 64])

In [62]:
# numpy.mod() 會將兩個形狀相同的陣列元素相」，取得「餘數」後成為新陣列。
a = np.array([2,3,4])
b = np.array([3,3,3])
np.mod(a,b)

array([2, 0, 1])

In [64]:
# numpy.reciprocal() 會回傳陣列中所有元素的「倒數」為新陣列
a = np.array([2., 3., 4., 5., 6.])
np.reciprocal(a)

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667])

In [65]:
# numpy.positive()、numpy.negative() 會將陣列元素乘以 1 或乘以 -1 後，回傳為新陣列
a = np.array([-2,-1,0,1,2])
np.positive(a), np.negative(a)

(array([-2, -1,  0,  1,  2]), array([ 2,  1,  0, -1, -2]))