# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [8]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print("資料")
print(X)
print("標籤")
print(y)


資料
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
標籤
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## 處理遺失值

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# missing_values=np.nan：指定缺失值的表示方式為 np.nan（即 NumPy 中的空值）。
# strategy='mean'：指定填補缺失值的策略為均值（mean）。這意味著所有的缺失值將被所在列的平均值替換。

imputer.fit(X[:, 1:3])
# 對數據集 X 的第 1 列和第 2 列（注意 Python 中的索引從 0 開始）進行擬合（fit）。也就是說，計算這些列的均值，以便之後用這些均值替換缺失值。
X[:, 1:3] = imputer.transform(X[:, 1:3])

X[:, 1:3]



array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 63777.77777777778],
       [35.0, 58000.0],
       [38.77777777777778, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

## 將資料進行熱處理

### Encoding the Independent Variable

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# 處理自變數
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

# 處理依變數：針對標籤進行編碼
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(X)
print(y)

[[0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


## 拆分資料訓練與測試集

In [15]:
# 將資料拆成兩成測試八成訓練
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print("資料訓練集")
print(X_test)
print("標籤訓練集")
print(y_train)


資料訓練集
[[1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
標籤訓練集
[0 1 0 0 1 1 0 1]


## Feature Scaling
- 將資料的值進行逼準化。
- 標準化將數據轉換為均值為 0，標準差為 1 的分佈，有助於提高模型的性能和收斂速度，尤其是對於使用梯度下降優化的算法（例如，線性回歸和神經網絡）。

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# 第三列（年齡）進行標準化
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

print("將年齡進行逼準化")
print(X_train)
print(X_test)

將年齡進行逼準化
[[1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 1.2909944487358056
  -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 1.0 -0.7745966692414834 1.7320508075688774 -0.7745966692414834
  -0.014117293757057777 -0.07013167641635372]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414834
  0.566708506533324 0.633562432710455]
 [1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 1.2909944487358056
  -0.30453019390224867 -0.30786617274297867]
 [1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 1.2909944487358056
  -1.9018011447007988 -1.420463615551582]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414834
  1.1475343068237058 1.232653363453549]
 [1.0 0.0 1.0 -0.7745966692414834 1.7320508075688774 -0.7745966692414834
  1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.7745966692414834
  -0.7401495441200351 -0.5646194287757332]]
[[1.0 0.0 1.0 -0.7745966692414834 1.7320508075688774 -0.7745966692